config/routes.rb
Rails.application.routes.draw do
  
  get 'braintrees/new'
  root "users#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings do 
    resource :bookings 
  end
  resources :bookings do 
    resource :braintree 
  end
  resources :users
  
  post 'braintrees/checkout'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # get '/search' => 'listings#search', as: 'search_listings'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Clearance.configure do |config|
    config.routes = false

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
	has_one :listing
	validates :start_date, :end_date, :overlap => {:scope => "listing_id"}
	
end

app/models/listing.rb
class Listing < ApplicationRecord

    	belongs_to :user
    	mount_uploader :images, ImagesUploader
    	has_many :bookings
    	

    	scope :bedrooms, ->(bedrooms) {where("bedrooms >= ?", bedrooms)}
    	scope :address, -> (address) {where("address ilike ?", "%#{address}%")}
    	# scope :price, -> (price) {where("price <= ?", price)}
    	scope :price_min, -> (min) {where("price >= ?", min)}
    	scope :price_max, -> (max) {where("price <= ?", max)}
    	
    	scope :verified, -> (verified) {where verified: true}

    	#"ilike as opposed to like in SQL makes the search query NOT case sensitive"


end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  mount_uploader :avatar, AvatarUploader

 has_many :authentications, dependent: :destroy

 # Role value relates to array index value.

 enum role:[:Customer, :Moderator, :Superadmin]

 def self.create_with_auth_and_hash(authentication, auth_hash)
  
   user = self.new(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.remote_avatar_url = auth_hash["info"]["image"]
   user.save
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def create 
		@booking = Booking.new(booking_params)
		
		@booking.user_id = current_user.id
		@booking.listing_id = params[:listing_id]
		@booking.days = @booking.end_date - @booking.start_date
		if @booking.days < 1 
			redirect_to "error"
		end
		@booking.total_price = @booking.days * Listing.find_by_id(params[:listing_id]).price
		
		

		if @booking.save 

			redirect_to new_booking_braintree_path(@booking.id)
		else
			redirect_to "error"
		end
	end

	def new
	end

	def show
		@booking = bookings.find(params[:id])
	end


	private 
	def booking_params

	params.require(:booking).permit(
		:start_date,
		:end_date,
		:listing_id,
		:days,
		:total_price
		)
	end
end

app/controllers/braintrees_controller.rb
class BraintreesController < ApplicationController
  def new
  	@booking_id = params[:booking_id]
    @total_amount = Booking.find_by_id(@booking_id).total_price
  	@client_token = Braintree::ClientToken.generate
  end



  def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
  
  @complete_booking= Booking.find_by_id(params[:checkout_form][:booking_id])

  result = Braintree::Transaction.sale(
   :amount => @complete_booking.total_price, #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true

    }

   )

  if result.success?
    # ReservationMailer.booking_email(current_user,@complete_booking).deliver_now
    ReservationMailer.booking_email(current_user,@complete_booking).deliver_later(wait: 1.minute)
    @complete_booking.payment_status = true
    @complete_booking.save

    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	
	def create
	
		@listings =Listing.new(listing_params)
		
		@listings.user_id = current_user.id

		if @listings.save
			redirect_to listings_path
		else 
			redirect_to "error"
		end

	end
	def new
      if !current_user.Customer?
        flash[:notice] = "Sorry. You are not allowed to perform this action."
        return redirect_to '/', notice: "Sorry. You do not have the permission to create a property."
      end
      # end authorization code

      # other code to make the new action work!
    end


	def index

		@listings = Listing.all.paginate(:page => params[:page], :per_page => 12)
		@listings = @listings.bedrooms(params[:bedrooms]) if params[:bedrooms].present?
		@listings = @listings.address(params[:address]) if params[:address].present?
		
		@listings = @listings.price_min(params[:min]) if params[:min].present?
		@listings = @listings.price_max(params[:max]) if params[:max].present?
		@listings = @listings.verified(params[:verified]) if params[:verified] == '1'

	end

	def show
		@listing = Listing.find(params[:id])
		
	end






	private 
	def listing_params

	params.require(:listing).permit(
		:title,
		:description,
		:address,
		:property_type,
		:accomodation_type,
		:bedrooms,
		:occupant_limit,
		:images,
		:price,
		:verified
		)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = root_url
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def show
		@user =User.find(params[:id])
		@listing = Listing.all.where("user_id = #{params[:id]}")
		@booking = Booking.all.where("user_id = #{params[:id]}")
	end


private

	def user_params
		params.require(:user).permit(
		:name,
		:email,
		:avatar,
		:password
		)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper

end

app/views/bookings/_form.html.erb
<div class="text-field">
  <%= form.label :start_date %>
  <%= form.text_field :start_date, type: 'date' %>
</div>

<div class="text-field">
  <%= form.label :end_date %>
  <%= form.text_field :end_date, type: 'date' %>
</div>

app/views/bookings/index.html.erb
This is where all bookings should show

app/views/bookings/new.html.erb
<div id="booking" class="new_booking">
  <h2>Make a new booking at <%=Listing.find_by_id(params[:listing_id]).title%></h2>
  <h3>At a cost per day of $<%=Listing.find_by_id(params[:listing_id]).price%> </h3>

    <%= form_with url: listing_bookings_path,scope: :booking, method: :post, local: true do |form| %>
    <%= render partial: '/bookings/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Check Dates" %>
    </div>

    <%end%>

app/views/bookings/show.html.erb
This is where the booking should show

app/views/braintrees/new.html.erb
<h2> Make a payment</h2>
<div class="demo-frame col-2">


  <%= form_for :checkout_form, url: braintrees_checkout_path, html: { id: "cardForm"} do |form| %>
<%= form.hidden_field :booking_id, :value => @booking_id %>
    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>
    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>
    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>
    <%= form.hidden_field "payment_method_nonce" %>

    Total to be paid: $<%=@total_amount%>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>





<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  

  

</head>
<body class='body justify-content-center'>
  <div class="header">



    <ul class="nav justify-content-center">
    <% if signed_in? -%>
      <li><%= button_to t(".sign_out"), sign_out_path, method: :delete %></li>
      <li><%= button_to ("Create new listing"), new_listing_path, method: :get %></li>
      <% user = current_user%>
      <li><%= button_to ("Listings"), listings_path, method: :get%></li>
        <%if current_user.avatar.url != nil%>
        <% profile_image = current_user.avatar.url %>
        <%else%>
        <% profile_image = "avatar.png" %>
        <%end%>
        <a href="<%= "/users/#{User.find_by_id(current_user.id).id}" %>"><%=image_tag (profile_image), style: 'position: absolute; right: 20vw; height:8vh; width:auto; border-radius: 100px'%></a>
      Welcome back <%=user.name%>! You're a <%=user.role%>!



    <% else -%>
      <li><%= link_to t(".sign_in"), sign_in_path %></li>
      <li><%= link_to "Sign in with Google", "/auth/google_oauth2" %></li>
      Welcome! Please sign in/up.
    <% end -%>
  </ul>
    
  </div>

<% if signed_in? -%>
  <div class = "nav justify-content-center">
  <%= form_with url: listings_path, method: :get, remote: true do |form| %>
    <div class="text-field">
  <%= form.label :Location %>
  <%= form.text_field :address %>
  <%= form.text_field :min, placeholder: "min price"%>
  <%= form.text_field :max,placeholder: "max price" %>
  <%= form.label :verified %>
  <%= form.check_box :verified %>
  <%= form.label :bedrooms %>
  <%= form.text_field :bedrooms %>

 <%=form.submit("Search", name: nil) %>
<%end%>
</div>
<%end%>





  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
</div>


  <%= yield %>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="text-field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div class="text-field">
  <%= form.label :price %>
  <%= form.text_field :price %>

<div class="text-field">
  <%= form.label :address %>
  <%= form.text_field :address%>
</div>

<div class="text-field">
  <%= form.label :property_type %>
  <%= form.text_field :property_type %>
</div>

<div class="text-field">
  <%= form.label :accomodation_type %>
  <%= form.text_field :accomodation_type %>
</div>

<div class="text-field">
  <%= form.label :bedrooms %>
  <%= form.number_field :bedrooms%>
</div>

<div class="text-field">
  <%= form.label :occupant_limit %>
  <%= form.number_field :occupant_limit%>
</div>

<div class="img-field">
  <%= form.label :images%>
  <%= form.file_field :images %>

</div>

<div class="img-field">
  <%= form.label :images%>
  <%= form.text_field :remote_images_url %>
</div>

app/views/listings/_listing.html.erb
<div class = "paginate_index "><%= will_paginate @listings, remote: true %></div>

	
	<div class = "album py-5 bg-light ">
		<div class = "container ">
			<div class ="row ">



		<%@listings.order("id").each do |x| %>
			<div class="justify-content-center col-xl-4 col-lg-6 col-md-12">
				<h4>
					<a href="<%= "/listings/#{x.id}" %>"><%= x.title %></a>
					<%if x.verified == true %>
					<%=image_tag 'verified.png', style: 'height:20px;width:auto;'%>
					<%end%>
				</h4>



				<h5>Listing #<%= x.id %> by <a href="<%= "/users/#{User.find(x.user_id).id}" %>"><%=User.find_by_id(x.user_id).name%></a>
				</h5>

				

				<div class="justify-content-center col-mb-4 shadow-sm ">
					<%if x.images.url == nil %>
						<%else%>
							<%= image_tag(x.images.url)%>
						<%end%></br>

					<b>Price per day:</b> $<%=x.price%> </br></br>
					Property type: <%= x.property_type %> </br>
					<%= x.description %>
						
				</div>



					</br>
					</br>
					</br>
			</div>

			<%end%>
		</div>
	</div>


<div class = "paginate_index"><%= will_paginate @listings %></div>

app/views/listings/_searchbar.html.erb
<%=form_for @listings do |form| %>

  <%= form.input :address %>
  <%= form.input :price %>
  <%= form.input :verified %>
  <%= form.input :bedrooms %>
  <%end%>

app/views/listings/index.html.erb
				<%if @listings.count < 1%>
			</br> </br>
				<h2>There are no listings that match your search</h2>
				<a href="<%="/listings"%>">Back to all listings</a>
				<%end%>


<div class = "sort_paginate_ajax"><%= render 'listing'%> </div>


<script>
   $(function(){
     $('.pagination a').attr('data-remote', 'true')
   });
 </script>

app/views/listings/index.js.erb
// $('.sort_paginate_ajax').html("<%= escape_javascript(render("listing"))%>")

 $(".sort_paginate_ajax").html('<%=  escape_javascript(render :partial => 'listing') %>');
$('.pagination a').attr('data-remote', 'true');

app/views/listings/new.html.erb
<div id="listing" class="new_listing">
  <h2>Setup your new listing!</h2>

    <%= form_with url: listings_path,scope: :listing, method: :post, local: true do |form| %>
    <%= render partial: '/listings/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <%end%>

app/views/listings/show.html.erb
<div class="listings">
<h3>Listing #<%= @listing.id %>
<%= @listing.title %><%if @listing.verified == true %>
<%=image_tag 'verified.png', style: 'height:20px;width:auto;'%>
<%end%></h3>
 <h4>Created by <a href="<%= "/users/#{User.find(@listing.user_id).id}" %>"><%=User.find_by_id(@listing.user_id).name%></a></h4>
 <h4>Price per day <%=@listing.price%></h4>

<h4>Located at: <%=@listing.address%> </h4>
This property is a <%= @listing.property_type %>. </br>

This is a <%=@listing.accomodation_type%> accomodation.
</br>

This accomodation can hold up to <%=@listing.occupant_limit%> guests and has <%=@listing.bedrooms%> bedrooms.

<h4> Property Description</h4>
<%= @listing.description %>
<%if @listing.images.url == nil %>
<%else%>
<%= image_tag(@listing.images.url)%>
<%end%>

<%= button_to ("Book"), new_listing_bookings_path(@listing.id), method: :get %>

</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'name' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>


<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="img-field">
  <%= form.label :avatar%>
  <%= form.file_field :avatar%>

</div>

<div class="img-field">
  <%= form.label :avatar%>
  <%= form.text_field :remote_avatar_url%>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="users">
<h3>User #<%= @user.id %>
 <h4><a href="<%= "/users/#{User.find(@user.id).id}" %>"><%=User.find_by_id(@user.id).name%></a></h4>
<%if @user.avatar.url != nil %>
<%profile_image  = @user.avatar.url%>
<%else%>
<% profile_image = "avatar.png" %>
<%end%>
<%=image_tag (profile_image), style: 'height: 200px;width:auto;'%>
<h5>Contact:  <%=@user.email%> </h5> 

<h4><u>My Bookings</u></h4>
<%@booking.each do |b| %>
<div= class="bookings">
<h5> <a href="<%= "/listings/#{b.listing_id}"%>"> <%=Listing.find_by_id("#{b.listing_id}").title%></a></h5>
<p>Address: <%=Listing.find_by_id("#{b.listing_id}").address%> </p>
<p>From <%=b.start_date%> to <%=b.end_date%> </br>
Total Price: $<%=b.total_price%> </p>

Hosted by: <a href="<%= "/users/#{Listing.find_by_id("#{b.listing_id}").user_id}"%>"> <%=User.find_by_id("#{Listing.find_by_id("#{b.listing_id}").user_id}").name%></a>



<%end%>
</br>
</br>

<h4><u>My Listings</u></h4>


<%@listing.each do |x| %>
<div class="listings">
<h5>Listing #<%= x.id %> </h5>
<h5><a href="<%= "/listings/#{x.id}" %>"><%= x.title %></a><%if x.verified == true %>
<%=image_tag 'verified.png', style: 'height:20px;width:auto;'%>
<%end%></h5>

<%= x.property_type %>
</br>

<%= x.description %>



</div>
<%end%>


</div>